In [1]:
import pandas as pd 

df = pd.read_csv('/home/adnane/Desktop/SOH_mlops/data/processed/lab/lab.csv')
df.head()

,cell_index,cell_id,cycle_index,t40_50,t50_60,t60_70,t70_80,t80_90,t90_100,SOH_hist,voltage_mean,voltage_std,current_mean,current_std,max_temp_mean,min_temp_std,voltage_slope,max_cell_voltage_at_80
0,1,2017-05-12_cell_001,2,97.419646,97.325944,97.365133,97.382747,356.974578,925.018041,0.973354,3.373283,0.328839,1.890932,1.540057,31.260827,0.991238,0.000334,3.533124
1,1,2017-05-12_cell_001,3,97.434044,97.430493,97.409614,97.424983,358.427110,923.159592,0.974455,3.379292,0.318187,1.875324,1.555370,31.292696,1.001907,0.000320,3.532701
2,1,2017-05-12_cell_001,4,97.456765,97.498881,97.474402,97.483221,359.805609,921.309290,0.975009,3.374663,0.322218,1.891820,1.551612,31.309947,1.000701,0.000326,3.531959
3,1,2017-05-12_cell_001,5,97.514138,97.538705,97.537601,97.553790,361.274545,919.357547,0.975613,3.375080,0.325033,1.830765,1.537852,31.360074,0.993087,0.000332,3.531786
4,1,2017-05-12_cell_001,6,97.610194,97.570431,97.577027,97.591275,362.426332,917.806739,0.975978,3.378655,0.319184,1.870990,1.554969,31.329521,1.025991,0.000321,3.530866

In [2]:
df.shape

(114688, 18)

In [3]:
df_2 = pd.read_csv('/home/adnane/Desktop/SOH_mlops/data/processed/data4/real_ev.csv')
df_2.head()

,car,charge_segment,capacity,t40_50,t50_60,t60_70,t70_80,t80_90,t90_100,SOH_hist,...,temp_diff_std,mileage,SOH_ref,mask_t40_50,mask_t50_60,mask_t60_70,mask_t70_80,mask_t80_90,mask_t90_100,mask_v80
0,2,8,44.143950,0.0,0.0,2730.0,2740.0,2560.0,0.0,1.011410,...,0.461966,1662.144,0.968790,0,0,1,1,1,0,1
1,2,10,43.516932,0.0,0.0,0.0,2890.0,2670.0,0.0,0.997044,...,0.455936,1958.880,0.968750,0,0,0,1,1,0,1
2,2,27,37.809852,0.0,0.0,2860.0,2860.0,2610.0,0.0,0.866285,...,0.458486,4832.256,0.968707,0,0,1,1,1,0,1
3,2,39,43.115402,0.0,0.0,2730.0,0.0,0.0,0.0,0.987844,...,0.414978,8690.880,0.968661,0,0,1,0,0,0,0
4,2,42,43.115402,2730.0,2740.0,2740.0,2730.0,2250.0,0.0,0.987844,...,0.451089,9028.800,0.968611,1,1,1,1,1,0,1

In [5]:
df_2.shape

(13677, 35)

In [7]:
df_2.columns

Index(['car', 'charge_segment', 'capacity', 't40_50', 't50_60', 't60_70',
       't70_80', 't80_90', 't90_100', 'SOH_hist', 'voltage_mean',
       'voltage_std', 'current_mean', 'current_std', 'max_temp_mean',
       'min_temp_std', 'voltage_slope', 'max_cell_voltage_at_80',
       'max_voltage_mean', 'max_voltage_std', 'min_voltage_mean',
       'min_voltage_std', 'min_temp_mean', 'voltage_diff_mean',
       'voltage_diff_std', 'temp_diff_std', 'mileage', 'SOH_ref',
       'mask_t40_50', 'mask_t50_60', 'mask_t60_70', 'mask_t70_80',
       'mask_t80_90', 'mask_t90_100', 'mask_v80'],
      dtype='object')

In [8]:
35-7-3

25

In [ ]:
now for training take the @training and rewrite the code in a simple way and dont gard code  things use config.yaml
write there the hyperparams and information about the model and add mlflow, we will connect mlflow with amazon s3 and amazon ec2 to run the mlflow server, u will find the mlflow uri inside an .env file